import { AnatomicalNode } from '../types/anatomy.ts';

export type SkullDivision = 'neurocranium' | 'viscerocranium';

export interface SkullAnatomicalNode extends AnatomicalNode {
  division: SkullDivision;
  paired: boolean; // Se é um osso par (direito/esquerdo) ou ímpar (sagital mediano)
}

/**
 * Catálogo canônico dos 22 ossos do crânio humano conforme a Terminologia Anatomica internacional e FMA.
 * 8 ossos do Neurocrânio (proteção do encéfalo) + 14 ossos do Viscerocrânio (esqueleto facial).
 */
export const CRANIUM_22_NODES: SkullAnatomicalNode[] = [
  // ==========================================
  // NEUROCRÂNIO (8 Ossos)
  // ==========================================
  {
    id: 'fma:os_frontale',
    fmaId: 'FMA:52734',
    namePtBr: 'Osso Frontal',
    nameLatin: 'Os frontale',
    chapter: 2,
    systemName: 'Sistema Esquelético',
    parentId: 'fma:calvaria',
    meshName: 'frontal_bone',
    division: 'neurocranium',
    paired: false,
    colorHex: '#eab308',
    explosionVector: { x: 0, y: 0.65, z: 1.1 },
    explosionMagnitudeMultiplier: 1.25,
    clinicalData: {
      origin: 'Glabela, arcos superciliares e margem supraorbital',
      insertion: 'Articula-se com parietais (sutura coronal), nasal, zigomático e esfenoide',
      clinicalSignificance: 'Forma a fronte e o teto da órbita; abriga os seios frontais, frequente sítio de sinusite e fraturas craniofaciais.',
    },
  },
  {
    id: 'fma:os_parietale_dexter',
    fmaId: 'FMA:52735',
    namePtBr: 'Osso Parietal Direito',
    nameLatin: 'Os parietale dextrum',
    chapter: 2,
    systemName: 'Sistema Esquelético',
    parentId: 'fma:calvaria',
    meshName: 'parietal_bone_r',
    division: 'neurocranium',
    paired: true,
    colorHex: '#38bdf8',
    explosionVector: { x: 1.15, y: 0.75, z: 0 },
    explosionMagnitudeMultiplier: 1.1,
    clinicalData: {
      origin: 'Eminência parietal e linhas temporais superior/inferior',
      insertion: 'Sutura sagital (com parietal E), coronal (com frontal) e lambdóidea (com occipital)',
      clinicalSignificance: 'Forma o ápice da calvária; ponto anatômico do bregma na fontanela anterior do recém-nascido.',
    },
  },
  {
    id: 'fma:os_parietale_sinister',
    fmaId: 'FMA:52736',
    namePtBr: 'Osso Parietal Esquerdo',
    nameLatin: 'Os parietale sinistrum',
    chapter: 2,
    systemName: 'Sistema Esquelético',
    parentId: 'fma:calvaria',
    meshName: 'parietal_bone_l',
    division: 'neurocranium',
    paired: true,
    colorHex: '#38bdf8',
    explosionVector: { x: -1.15, y: 0.75, z: 0 },
    explosionMagnitudeMultiplier: 1.1,
    clinicalData: {
      origin: 'Eminência parietal esquerda',
      insertion: 'Articula-se medialmente com o parietal direito na sutura sagital',
      clinicalSignificance: 'Protege a área somatossensorial e motora parietal do hemisfério dominante.',
    },
  },
  {
    id: 'fma:os_occipitale',
    fmaId: 'FMA:52737',
    namePtBr: 'Osso Occipital',
    nameLatin: 'Os occipitale',
    chapter: 2,
    systemName: 'Sistema Esquelético',
    parentId: 'fma:cranium',
    meshName: 'occipital_bone',
    division: 'neurocranium',
    paired: false,
    colorHex: '#818cf8',
    explosionVector: { x: 0, y: 0.35, z: -1.25 },
    explosionMagnitudeMultiplier: 1.2,
    clinicalData: {
      origin: 'Protuberância occipital externa (inion) e côndilos occipitais',
      insertion: 'Articula-se com atlas (C1) e parietais (sutura lambdóidea)',
      clinicalSignificance: 'Contém o forame magno para passagem do bulbo encefálico e artérias vertebrais; local da junção craniocervical.',
    },
  },
  {
    id: 'fma:os_temporale_dexter',
    fmaId: 'FMA:52738',
    namePtBr: 'Osso Temporal Direito',
    nameLatin: 'Os temporale dextrum',
    chapter: 2,
    systemName: 'Sistema Esquelético',
    parentId: 'fma:cranium',
    meshName: 'temporal_bone_r',
    division: 'neurocranium',
    paired: true,
    colorHex: '#06b6d4',
    explosionVector: { x: 1.2, y: -0.15, z: -0.15 },
    explosionMagnitudeMultiplier: 1.15,
    clinicalData: {
      origin: 'Processo mastoide, processo estiloide e parte petrosa',
      insertion: 'Forma a fossa mandibular para a ATM com a mandíbula',
      clinicalSignificance: 'Abriga o aparelho vestíbulo-coclear (audição e equilíbrio) e o canal carótico.',
    },
  },
  {
    id: 'fma:os_temporale_sinister',
    fmaId: 'FMA:52739',
    namePtBr: 'Osso Temporal Esquerdo',
    nameLatin: 'Os temporale sinistrum',
    chapter: 2,
    systemName: 'Sistema Esquelético',
    parentId: 'fma:cranium',
    meshName: 'temporal_bone_l',
    division: 'neurocranium',
    paired: true,
    colorHex: '#06b6d4',
    explosionVector: { x: -1.2, y: -0.15, z: -0.15 },
    explosionMagnitudeMultiplier: 1.15,
    clinicalData: {
      origin: 'Parte escamosa, petrosa e timpânica esquerda',
      insertion: 'Articula-se com o parietal e asa maior do esfenoide (pterion)',
      clinicalSignificance: 'Região do pterion: passagem da artéria meníngea média; trauma nesta região pode causar hematoma epidural.',
    },
  },
  {
    id: 'fma:os_sphenoidale',
    fmaId: 'FMA:52741',
    namePtBr: 'Osso Esfenoide',
    nameLatin: 'Os sphenoidale',
    chapter: 2,
    systemName: 'Sistema Esquelético',
    parentId: 'fma:cranium',
    meshName: 'sphenoid_bone',
    division: 'neurocranium',
    paired: false,
    colorHex: '#a855f7',
    explosionVector: { x: 0, y: 0.1, z: 0.4 },
    explosionMagnitudeMultiplier: 0.85,
    clinicalData: {
      origin: 'Corpo do esfenoide, asas maiores e menores, processos pterigóides',
      insertion: 'Conecta todos os ossos do neurocrânio entre si ("pedra fundamental")',
      clinicalSignificance: 'Acomoda a sela túrcica (fossa hipofisária para a glândula hipófise) e canais ópticos para os nervos ópticos (NC II).',
    },
  },
  {
    id: 'fma:os_ethmoidale',
    fmaId: 'FMA:52742',
    namePtBr: 'Osso Etmoide',
    nameLatin: 'Os ethmoidale',
    chapter: 2,
    systemName: 'Sistema Esquelético',
    parentId: 'fma:cranium',
    meshName: 'ethmoid_bone',
    division: 'neurocranium',
    paired: false,
    colorHex: '#6366f1',
    explosionVector: { x: 0, y: 0.3, z: 0.8 },
    explosionMagnitudeMultiplier: 0.9,
    clinicalData: {
      origin: 'Lâmina crivosa (cribriforme), crista galli e lâmina perpendicular',
      insertion: 'Articula-se com o frontal, vômer e esfenóide',
      clinicalSignificance: 'Perfurado pelos filetes do nervo olfatório (NC I); fraturas de base anterior podem gerar fístula liquórica (rinorreia de líquor).',
    },
  },

  // ==========================================
  // VISCEROCRÂNIO (14 Ossos da Face)
  // ==========================================
  {
    id: 'fma:maxilla_dextra',
    fmaId: 'FMA:52743',
    namePtBr: 'Maxila Direita',
    nameLatin: 'Maxilla dextra',
    chapter: 2,
    systemName: 'Sistema Esquelético',
    parentId: 'fma:viscerocranium',
    meshName: 'maxilla_r',
    division: 'viscerocranium',
    paired: true,
    colorHex: '#ec4899',
    explosionVector: { x: 0.45, y: -0.3, z: 1.0 },
    explosionMagnitudeMultiplier: 1.05,
    clinicalData: {
      origin: 'Processo alveolar, processo palatino e corpo maxilar',
      insertion: 'Articula-se na linha mediana com a maxila contralateral',
      clinicalSignificance: 'Abriga o seio maxilar e a arcada dentária superior; sede de fraturas de Le Fort I, II e III.',
    },
  },
  {
    id: 'fma:maxilla_sinistra',
    fmaId: 'FMA:52744',
    namePtBr: 'Maxila Esquerda',
    nameLatin: 'Maxilla sinistra',
    chapter: 2,
    systemName: 'Sistema Esquelético',
    parentId: 'fma:viscerocranium',
    meshName: 'maxilla_l',
    division: 'viscerocranium',
    paired: true,
    colorHex: '#ec4899',
    explosionVector: { x: -0.45, y: -0.3, z: 1.0 },
    explosionMagnitudeMultiplier: 1.05,
    clinicalData: {
      origin: 'Processo frontal e zigomático esquerdo',
      insertion: 'Forma parte do soalho da cavidade nasal e da órbita esquerda',
      clinicalSignificance: 'Suporte mastigatório superior esquerdo e cavidade do seio maxilar.',
    },
  },
  {
    id: 'fma:os_zygomaticum_dexter',
    fmaId: 'FMA:52745',
    namePtBr: 'Osso Zigomático Direito',
    nameLatin: 'Os zygomaticum dextrum',
    chapter: 2,
    systemName: 'Sistema Esquelético',
    parentId: 'fma:viscerocranium',
    meshName: 'zygomatic_bone_r',
    division: 'viscerocranium',
    paired: true,
    colorHex: '#f97316',
    explosionVector: { x: 1.1, y: -0.2, z: 0.7 },
    explosionMagnitudeMultiplier: 1.1,
    clinicalData: {
      origin: 'Corpo do osso malar direito',
      insertion: 'Articula-se com o processo zigomático do temporal formando o arco zigomático',
      clinicalSignificance: 'Responsável pela proeminência malar da face; ponto de inserção do músculo masseter.',
    },
  },
  {
    id: 'fma:os_zygomaticum_sinister',
    fmaId: 'FMA:52746',
    namePtBr: 'Osso Zigomático Esquerdo',
    nameLatin: 'Os zygomaticum sinistrum',
    chapter: 2,
    systemName: 'Sistema Esquelético',
    parentId: 'fma:viscerocranium',
    meshName: 'zygomatic_bone_l',
    division: 'viscerocranium',
    paired: true,
    colorHex: '#f97316',
    explosionVector: { x: -1.1, y: -0.2, z: 0.7 },
    explosionMagnitudeMultiplier: 1.1,
    clinicalData: {
      origin: 'Malar esquerdo e parede ântero-lateral da órbita',
      insertion: 'Forma o arco zigomático esquerdo',
      clinicalSignificance: 'Fraturas em tripé (zigomático-maxilar) são frequentes em traumas contusos faciais.',
    },
  },
  {
    id: 'fma:os_nasale_dexter',
    fmaId: 'FMA:52749',
    namePtBr: 'Osso Nasal Direito',
    nameLatin: 'Os nasale dextrum',
    chapter: 2,
    systemName: 'Sistema Esquelético',
    parentId: 'fma:viscerocranium',
    meshName: 'nasal_bone_r',
    division: 'viscerocranium',
    paired: true,
    colorHex: '#14b8a6',
    explosionVector: { x: 0.2, y: 0.1, z: 1.3 },
    explosionMagnitudeMultiplier: 1.15,
    clinicalData: {
      origin: 'Ponte nasal direita',
      insertion: 'Sutura internasal medialmente e osso frontal superiormente',
      clinicalSignificance: 'Osso mais fraturado da face humana em acidentes automobilísticos e agressões.',
    },
  },
  {
    id: 'fma:os_nasale_sinister',
    fmaId: 'FMA:52750',
    namePtBr: 'Osso Nasal Esquerdo',
    nameLatin: 'Os nasale sinistrum',
    chapter: 2,
    systemName: 'Sistema Esquelético',
    parentId: 'fma:viscerocranium',
    meshName: 'nasal_bone_l',
    division: 'viscerocranium',
    paired: true,
    colorHex: '#14b8a6',
    explosionVector: { x: -0.2, y: 0.1, z: 1.3 },
    explosionMagnitudeMultiplier: 1.15,
    clinicalData: {
      origin: 'Ponte nasal esquerda',
      insertion: 'Sutura com a cartilagem lateral do nariz inferiormente',
      clinicalSignificance: 'Sustenta o dorso superior da pirâmide nasal.',
    },
  },
  {
    id: 'fma:os_lacrimale_dexter',
    fmaId: 'FMA:52751',
    namePtBr: 'Osso Lacrimal Direito',
    nameLatin: 'Os lacrimale dextrum',
    chapter: 2,
    systemName: 'Sistema Esquelético',
    parentId: 'fma:viscerocranium',
    meshName: 'lacrimal_bone_r',
    division: 'viscerocranium',
    paired: true,
    colorHex: '#0ea5e9',
    explosionVector: { x: 0.35, y: 0.15, z: 0.9 },
    explosionMagnitudeMultiplier: 1.0,
    clinicalData: {
      origin: 'Parede medial da órbita direita',
      insertion: 'Sulco lacrimal com a maxila',
      clinicalSignificance: 'Aloja o saco lacrimal para drenagem das lágrimas para a cavidade nasal (meato inferior).',
    },
  },
  {
    id: 'fma:os_lacrimale_sinister',
    fmaId: 'FMA:52752',
    namePtBr: 'Osso Lacrimal Esquerdo',
    nameLatin: 'Os lacrimale sinistrum',
    chapter: 2,
    systemName: 'Sistema Esquelético',
    parentId: 'fma:viscerocranium',
    meshName: 'lacrimal_bone_l',
    division: 'viscerocranium',
    paired: true,
    colorHex: '#0ea5e9',
    explosionVector: { x: -0.35, y: 0.15, z: 0.9 },
    explosionMagnitudeMultiplier: 1.0,
    clinicalData: {
      origin: 'Menor e mais frágil osso da face humana',
      insertion: 'Articula-se com o osso etmoide e a concha nasal inferior',
      clinicalSignificance: 'Canal nasolacrimal; obstruções causam epífora (lacrimejamento constante).',
    },
  },
  {
    id: 'fma:os_palatinum_dexter',
    fmaId: 'FMA:52753',
    namePtBr: 'Osso Palatino Direito',
    nameLatin: 'Os palatinum dextrum',
    chapter: 2,
    systemName: 'Sistema Esquelético',
    parentId: 'fma:viscerocranium',
    meshName: 'palatine_bone_r',
    division: 'viscerocranium',
    paired: true,
    colorHex: '#84cc16',
    explosionVector: { x: 0.3, y: -0.4, z: 0.2 },
    explosionMagnitudeMultiplier: 0.9,
    clinicalData: {
      origin: 'Lâmina horizontal e lâmina perpendicular em formato de L',
      insertion: 'Forma o terço posterior do palato duro (céu da boca)',
      clinicalSignificance: 'Passagem dos nervos palatinos maior e menor para anestesia odontológica.',
    },
  },
  {
    id: 'fma:os_palatinum_sinister',
    fmaId: 'FMA:52754',
    namePtBr: 'Osso Palatino Esquerdo',
    nameLatin: 'Os palatinum sinistrum',
    chapter: 2,
    systemName: 'Sistema Esquelético',
    parentId: 'fma:viscerocranium',
    meshName: 'palatine_bone_l',
    division: 'viscerocranium',
    paired: true,
    colorHex: '#84cc16',
    explosionVector: { x: -0.3, y: -0.4, z: 0.2 },
    explosionMagnitudeMultiplier: 0.9,
    clinicalData: {
      origin: 'Palato ósseo posterior esquerdo',
      insertion: 'Articula-se com o osso esfenoide e vômer',
      clinicalSignificance: 'Contribui para a fossa pterigopalatina e soalho da órbita.',
    },
  },
  {
    id: 'fma:concha_nasalis_inferior_dextra',
    fmaId: 'FMA:52755',
    namePtBr: 'Concha Nasal Inferior Direita',
    nameLatin: 'Concha nasalis inferior dextra',
    chapter: 2,
    systemName: 'Sistema Esquelético',
    parentId: 'fma:viscerocranium',
    meshName: 'inferior_nasal_concha_r',
    division: 'viscerocranium',
    paired: true,
    colorHex: '#10b981',
    explosionVector: { x: 0.35, y: -0.15, z: 0.65 },
    explosionMagnitudeMultiplier: 0.95,
    clinicalData: {
      origin: 'Parede lateral da cavidade nasal direita',
      insertion: 'Fixa-se à maxila e osso palatino',
      clinicalSignificance: 'Aquece, umidifica e filtra o ar inspirado; hipertrofia da concha causa obstrução respiratória crônica.',
    },
  },
  {
    id: 'fma:concha_nasalis_inferior_sinistra',
    fmaId: 'FMA:52756',
    namePtBr: 'Concha Nasal Inferior Esquerda',
    nameLatin: 'Concha nasalis inferior sinistra',
    chapter: 2,
    systemName: 'Sistema Esquelético',
    parentId: 'fma:viscerocranium',
    meshName: 'inferior_nasal_concha_l',
    division: 'viscerocranium',
    paired: true,
    colorHex: '#10b981',
    explosionVector: { x: -0.35, y: -0.15, z: 0.65 },
    explosionMagnitudeMultiplier: 0.95,
    clinicalData: {
      origin: 'Concha esponjosa óssea independente esquerda',
      insertion: 'Delimita o meato nasal inferior para o ducto nasolacrimal',
      clinicalSignificance: 'Alvo comum de turbinectomia e turbinoplastia por radiofrequência.',
    },
  },
  {
    id: 'fma:vomer',
    fmaId: 'FMA:52757',
    namePtBr: 'Vômer',
    nameLatin: 'Vomer',
    chapter: 2,
    systemName: 'Sistema Esquelético',
    parentId: 'fma:viscerocranium',
    meshName: 'vomer',
    division: 'viscerocranium',
    paired: false,
    colorHex: '#d946ef',
    explosionVector: { x: 0, y: -0.2, z: 0.4 },
    explosionMagnitudeMultiplier: 0.8,
    clinicalData: {
      origin: 'Lâmina óssea vertical fina trapezoidal',
      insertion: 'Forma a porção póstero-inferior do septo nasal ósseo',
      clinicalSignificance: 'Desvios de septo septoplásticos frequentemente envolvem o vômer e a cartilagem septal.',
    },
  },
  {
    id: 'fma:mandibula',
    fmaId: 'FMA:52748',
    namePtBr: 'Mandíbula',
    nameLatin: 'Mandibula',
    chapter: 2,
    systemName: 'Sistema Esquelético',
    parentId: 'fma:viscerocranium',
    meshName: 'mandible',
    division: 'viscerocranium',
    paired: false,
    colorHex: '#22c55e',
    explosionVector: { x: 0, y: -1.3, z: 0.45 },
    explosionMagnitudeMultiplier: 1.35,
    clinicalData: {
      origin: 'Corpo, sínfise mentual, ângulo e ramos da mandíbula',
      insertion: 'Côndilos mandibulares articulam-se na ATM bilateral com os ossos temporais',
      functionalAction: 'Mastigação, fala, deglutição e suporte aos 16 dentes inferiores',
      innervation: 'Nervo alveolar inferior e nervo mentual (ramos do NC V3)',
      clinicalSignificance: 'Único osso móvel do esqueleto craniofacial; fraturas de sínfise, ângulo e côndilo são urgências cirúrgicas bucomaxilofaciais.',
    },
  },
];
