import { AnatomicalNode } from '../types/anatomy.ts';

export type MuscleLayer = 'deep' | 'intermediate' | 'superficial' | 'skin';

export interface MuscleAnatomicalNode extends AnatomicalNode {
  layer: MuscleLayer;
  innervationNerve: string; // Ex: 'Nervo Trigêmeo (V3)' ou 'Nervo Facial (VII)'
  antagonistAction?: string;
}

/**
 * Catálogo canônico dos principais músculos mastigatórios e da mímica facial
 * (Capítulo 3: Miologia da Terminologia Anatomica internacional e FMA).
 */
export const CRANIOFACIAL_MUSCLES: MuscleAnatomicalNode[] = [
  // ==========================================
  // MÚSCULOS DA MASTIGAÇÃO (Inervados pelo NC V3)
  // ==========================================
  {
    id: 'fma:musculus_masseter_dexter',
    fmaId: 'FMA:49006',
    namePtBr: 'Músculo Masseter Direito',
    nameLatin: 'Musculus masseter dexter',
    chapter: 3,
    systemName: 'Sistema Muscular',
    meshName: 'masseter_r',
    layer: 'superficial',
    layerDepth: 2,
    colorHex: '#dc2626',
    innervationNerve: 'Nervo massetérico (ramo do NC V3 - Mandibular)',
    explosionVector: { x: 0.9, y: -0.3, z: 0.6 },
    explosionMagnitudeMultiplier: 1.1,
    clinicalData: {
      origin: 'Margem inferior e face medial do arco zigomático',
      insertion: 'Face lateral do ângulo e ramo da mandíbula',
      functionalAction: 'Poderosa elevação da mandíbula (fechamento da boca) e protusão',
      innervation: 'Nervo massetérico (Nervo Trigêmeo, divisão mandibular V3)',
      clinicalSignificance: 'Músculo mais potente da mastigação; hipertrofia massetérica causa mandíbula quadrada e está associada ao bruxismo crônico e trismo.',
    },
  },
  {
    id: 'fma:musculus_masseter_sinister',
    fmaId: 'FMA:49006',
    namePtBr: 'Músculo Masseter Esquerdo',
    nameLatin: 'Musculus masseter sinister',
    chapter: 3,
    systemName: 'Sistema Muscular',
    meshName: 'masseter_l',
    layer: 'superficial',
    layerDepth: 2,
    colorHex: '#dc2626',
    innervationNerve: 'Nervo massetérico (ramo do NC V3 - Mandibular)',
    explosionVector: { x: -0.9, y: -0.3, z: 0.6 },
    explosionMagnitudeMultiplier: 1.1,
    clinicalData: {
      origin: 'Arco zigomático esquerdo',
      insertion: 'Ângulo e ramo mandibular esquerdo',
      functionalAction: 'Oclusão forçada dos dentes e mastigação ipsilateral',
      innervation: 'Nervo massetérico (NC V3)',
      clinicalSignificance: 'Ponto frequente de aplicação de toxina botulínica para alívio de dor miofascial da ATM e afinamento facial.',
    },
  },
  {
    id: 'fma:musculus_temporalis_dexter',
    fmaId: 'FMA:49007',
    namePtBr: 'Músculo Temporal Direito',
    nameLatin: 'Musculus temporalis dexter',
    chapter: 3,
    systemName: 'Sistema Muscular',
    meshName: 'temporalis_r',
    layer: 'superficial',
    layerDepth: 2,
    colorHex: '#b91c1c',
    innervationNerve: 'Nervos temporais profundos (ramo do NC V3)',
    explosionVector: { x: 1.1, y: 0.6, z: 0 },
    explosionMagnitudeMultiplier: 1.15,
    clinicalData: {
      origin: 'Fossa temporal e face profunda da fáscia temporal',
      insertion: 'Ápice e face medial do processo coronoide da mandíbula',
      functionalAction: 'Fibras anteriores elevam a mandíbula; fibras posteriores horizontais retraem a mandíbula',
      innervation: 'Nervos temporais profundos anterior e posterior (NC V3)',
      clinicalSignificance: 'Cefaleia tensional e dor na ATM frequentemente irradiam para o ventre do músculo temporal.',
    },
  },
  {
    id: 'fma:musculus_temporalis_sinister',
    fmaId: 'FMA:49007',
    namePtBr: 'Músculo Temporal Esquerdo',
    nameLatin: 'Musculus temporalis sinister',
    chapter: 3,
    systemName: 'Sistema Muscular',
    meshName: 'temporalis_l',
    layer: 'superficial',
    layerDepth: 2,
    colorHex: '#b91c1c',
    innervationNerve: 'Nervos temporais profundos (ramo do NC V3)',
    explosionVector: { x: -1.1, y: 0.6, z: 0 },
    explosionMagnitudeMultiplier: 1.15,
    clinicalData: {
      origin: 'Fossa temporal esquerda até a linha temporal inferior',
      insertion: 'Processo coronoide da mandíbula esquerda',
      functionalAction: 'Elevação e retração da mandíbula',
      innervation: 'Nervos temporais profundos (NC V3)',
      clinicalSignificance: 'Músculo em leque palpável durante a mordida forçada nas têmporas.',
    },
  },
  {
    id: 'fma:musculus_pterygoideus_medialis',
    fmaId: 'FMA:49008',
    namePtBr: 'Músculo Pterigóideo Medial',
    nameLatin: 'Musculus pterygoideus medialis',
    chapter: 3,
    systemName: 'Sistema Muscular',
    meshName: 'pterygoideus_medialis',
    layer: 'deep',
    layerDepth: 1,
    colorHex: '#991b1b',
    innervationNerve: 'Nervo pterigóideo medial (ramo do NC V3)',
    explosionVector: { x: 0.35, y: -0.45, z: 0.2 },
    explosionMagnitudeMultiplier: 0.9,
    clinicalData: {
      origin: 'Face medial da lâmina lateral do processo pterigóide e tuberosidade da maxila',
      insertion: 'Face medial do ramo e ângulo da mandíbula (oposto ao masseter)',
      functionalAction: 'Trabalha em conjunto com o masseter para elevar e projetar a mandíbula; movimentos laterais de trituração',
      innervation: 'Nervo pterigóideo medial (NC V3)',
      clinicalSignificance: 'Forma uma cinta muscular ao redor do ângulo mandibular juntamente com o masseter ("chapeleta pterigomasseterina").',
    },
  },
  {
    id: 'fma:musculus_pterygoideus_lateralis',
    fmaId: 'FMA:49009',
    namePtBr: 'Músculo Pterigóideo Lateral',
    nameLatin: 'Musculus pterygoideus lateralis',
    chapter: 3,
    systemName: 'Sistema Muscular',
    meshName: 'pterygoideus_lateralis',
    layer: 'deep',
    layerDepth: 1,
    colorHex: '#991b1b',
    innervationNerve: 'Nervo pterigóideo lateral (ramo do NC V3)',
    explosionVector: { x: 0.4, y: -0.1, z: 0.3 },
    explosionMagnitudeMultiplier: 0.85,
    clinicalData: {
      origin: 'Cabeça superior: crista infratemporal do esfenoide; Cabeça inferior: face lateral do processo pterigóide',
      insertion: 'Fóvea pterigóidea no colo da mandíbula e cápsula/disco articular da ATM',
      functionalAction: 'Único músculo da mastigação que atua na abertura da boca (abaixamento) e protusão ativa do disco articular',
      innervation: 'Nervo pterigóideo lateral (NC V3)',
      clinicalSignificance: 'Principal implicado em estalos da ATM, luxação do disco articular e travamento da mandíbula em abertura.',
    },
  },

  // ==========================================
  // MÚSCULOS DA MÍMICA FACIAL (Inervados pelo NC VII - Facial)
  // ==========================================
  {
    id: 'fma:musculus_orbicularis_oculi',
    fmaId: 'FMA:46768',
    namePtBr: 'Músculo Orbicular do Olho',
    nameLatin: 'Musculus orbicularis oculi',
    chapter: 3,
    systemName: 'Sistema Muscular',
    meshName: 'orbicularis_oculi',
    layer: 'superficial',
    layerDepth: 2,
    colorHex: '#ef4444',
    innervationNerve: 'Ramos temporal e zigomático do Nervo Facial (NC VII)',
    explosionVector: { x: 0.4, y: 0.35, z: 1.15 },
    explosionMagnitudeMultiplier: 1.15,
    clinicalData: {
      origin: 'Parte palpebral, orbital e lacrimal ao redor da órbita',
      insertion: 'Pele periorbital e ligamento palpebral lateral',
      functionalAction: 'Esfíncter dos olhos: fecha as pálpebras suavemente (piscar) ou firmemente (proteção)',
      innervation: 'Nervo Facial (NC VII)',
      clinicalSignificance: 'Na Paralisia de Bell (paralisia facial periférica), o paciente perde a capacidade de fechar o olho (sinal de Bell), gerando risco de úlcera de córnea.',
    },
  },
  {
    id: 'fma:musculus_orbicularis_oris',
    fmaId: 'FMA:46830',
    namePtBr: 'Músculo Orbicular da Boca',
    nameLatin: 'Musculus orbicularis oris',
    chapter: 3,
    systemName: 'Sistema Muscular',
    meshName: 'orbicularis_oris',
    layer: 'superficial',
    layerDepth: 2,
    colorHex: '#ef4444',
    innervationNerve: 'Ramos bucal e marginal da mandíbula do Nervo Facial (NC VII)',
    explosionVector: { x: 0, y: -0.55, z: 1.1 },
    explosionMagnitudeMultiplier: 1.15,
    clinicalData: {
      origin: 'Maxila e mandíbula periorais, fibras intrínsecas dos lábios',
      insertion: 'Pele e mucosa dos lábios superior e inferior',
      functionalAction: 'Esfíncter oral: oclusão dos lábios, compressão e protrusão ("bico", assobiar, beijar)',
      innervation: 'Nervo Facial (NC VII)',
      clinicalSignificance: 'Essencial para a continência salivar, fala (fonemas labiais p, b, m) e mastigação.',
    },
  },
  {
    id: 'fma:musculus_buccinator',
    fmaId: 'FMA:46834',
    namePtBr: 'Músculo Bucinador',
    nameLatin: 'Musculus buccinator',
    chapter: 3,
    systemName: 'Sistema Muscular',
    meshName: 'buccinator',
    layer: 'intermediate',
    layerDepth: 1,
    colorHex: '#b91c1c',
    innervationNerve: 'Ramo bucal do Nervo Facial (NC VII)',
    explosionVector: { x: 0.65, y: -0.4, z: 0.75 },
    explosionMagnitudeMultiplier: 1.0,
    clinicalData: {
      origin: 'Processos alveolares da maxila e mandíbula, rafe pterigomandibular',
      insertion: 'Ângulo da boca (modíolo) fundindo-se ao orbicular da boca',
      functionalAction: 'Comprime as bochechas contra os dentes molares durante a mastigação (evita acúmulo de alimento); expulsa ar sob pressão (soprar/tocar instrumentos de sopro)',
      innervation: 'Nervo Facial (NC VII)',
      clinicalSignificance: 'Perfurado pelo ducto parotídeo (de Stensen) na altura do segundo molar superior.',
    },
  },
];
