extend type Notification {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Notification", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Notification`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "Notification.user", purpose: IMPLICIT_REF_FIELD)
}
extend type Process {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Process", purpose: IMPLICIT_KEY_FIELD)
}
extend type Requirement {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Requirement", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Requirement`.`process`. It must match the value of `Process`.`id`. See `@ref` for how to customize it.
  """
  processId: UUID @fdc_generated(from: "Requirement.process", purpose: IMPLICIT_REF_FIELD)
}
extend type Submission {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Submission", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Submission`.`requirement`. It must match the value of `Requirement`.`id`. See `@ref` for how to customize it.
  """
  requirementId: UUID! @fdc_generated(from: "Submission.requirement", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Submission`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "Submission.user", purpose: IMPLICIT_REF_FIELD)
}
extend type User {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "User", purpose: IMPLICIT_KEY_FIELD)
}
