type User @table {
  name: String!
  email: String!
  role: String! # Ex: "Clinician", "Student", "Admin"
}

type ClinicalBookmark @table {
  user: User!
  name: String!
  description: String
  viewType: String! # "realistic" | "exploded"
  activeRegion: String!
  solidOpacity: Float!
  explosionProgress: Float!
  selectedNodeId: String
  createdAt: Timestamp! @default(expr: "request.time")
}

type ClinicalAnnotation @table {
  bookmark: ClinicalBookmark!
  structureId: String! # Ex: "za:frontal_bone"
  noteText: String!
  author: User!
  createdAt: Timestamp! @default(expr: "request.time")
}